# Generated by Django 2.2.6 on 2019-10-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userConfirmation', '0003_imgupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgupload',
            old_name='filepath',
            new_name='filename',
        ),
    ]
