# Generated by Django 2.2.7 on 2019-11-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userConfirmation', '0004_auto_20191030_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('denominacion', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('e', models.CharField(max_length=100)),
                ('id_inventario', models.CharField(max_length=100)),
            ],
        ),
    ]
