# Generated by Django 2.2.7 on 2019-12-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userConfirmation', '0005_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
