# Generated by Django 2.2.7 on 2019-12-07 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userConfirmation', '0008_auto_20191207_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='codigo_barcode',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userConfirmation.BarCode', unique=True),
        ),
    ]
