# Generated by Django 2.2.7 on 2019-12-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userConfirmation', '0012_auto_20191207_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userConfirmation.BarCode'),
        ),
    ]
